DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;


CREATE TABLE favoriteChannels(
id INT AUTO_INCREMENT,
channel VARCHAR (30),
PRIMARY KEY (id)
)

